apiVersion: v1
kind: Pod
metadata:
  name: jenkins-hari
spec:
  containers:
  - name: jenkins-democlass
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
      hostPort: 8091
