apiVersion: apps/v1 #extensions/v1beta1 for before v1.16
kind: ReplicaSet
metadata:
  name: test-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [Bugfix]}
      - {key: env, operator: NotIn, values: [Liveproduction]}
  template:
    metadata:
      labels:
        app: Bugfix
        env: devlopment
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80
